### ISSUE TITLE
what's the state of this implementation?

### ISSUE THREAD

**Issue by szha** [jongchyisu/pix-nn#1]
thanks

**Comment by jongchyisu** [comment]
Hi Zha Cheng, so far the result is still not as good as the pytorch implementation from the author. I didn't continue this implementation for a while, since I changed to pytorch and my internship ended two weeks ago, and now I am currently working on something else.

**Comment by szha** [comment]
I see. Would you like to submit this to mxnet repo so that others can take a look?

**Comment by jongchyisu** [comment]
Could you tell me where exactly I should submit to? The code is kind of messy though

**Comment by szha** [comment]
You can submit it to mxnet/example/gluon/pix2pix in a pull request, and describe what's in the code and what's the problem.

**Comment by jongchyisu** [comment]
I saw the implementation on 
http://thestraightdope.mxnet.io/chapter14_generative-adversarial-networks/pixel2pixel.html
I guess that's working?

**Comment by jongchyisu** [comment]
Cool, sorry that I didn't help...

**Comment by szha** [comment]
No worries. Your implementation provided an awesome base to improve on. Thanks for the great job.
